### ISSUE TITLE
Замечания по стилю

### ISSUE THREAD

**Issue by Primetalk** [WillySanych/Search-for-duplicates#2]
1. Нет необходимости использовать `var` для тех объектов, которые не будут изменяться. Что вы думаете насчёт `val`?
2. Некоторые имена переменных и функций вводят в заблуждение и не отражают содержание. Например, `Array` - ничего не говорит о том, что происходит. Хуже того, это имя совпадает с именем `Array[_]` , имеющемся в Scala. Обычно для функций используют переходные глаголы. Например, `parseArray`, или `readCollection`.. 
3. Рекурсия для обработки ошибок не является рекомендуемой практикой. Почему бы не использовать исключения `throw new IllegalArgumentException("...")`?
4. Рекурсия внутри цикла -  https://github.com/WillySanych/Search-for-duplicates/blob/master/src/main/scala/Main.scala#L39-L42 - что произойдёт, если в первом массиве будет больше одной ошибки диапазона?
5. Как вы думаете, что означает слово `amount`?

**Comment by WillySanych** [comment]
Исправил, постарался учесть все ваши замечания

**Comment by Primetalk** [comment]
Отлично.

**Comment by Primetalk** [comment]
1. Чем отличаются `&&` и `&`?
2. Есть такая функция в коллекциях `forall`.
